feat: validate and store all identity keys instead of the first one
dashevo/js-dpp pull request #234
Opened 2020-09-10 10:15 UTC by shuplenkov

## Issue being fixed or feature implemented

## What was done?

Validate and store all identity keys instead of the first one

## How Has This Been Tested?

Unit tests

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2020-09-10 11:12 UTC, shumkov commented on lib/StateRepositoryInterface.js
> + * @name StateRepository#storeIdentityIdPublicKeys
`storeIdentityIdPublicKeyHashes` ?

2020-09-10 11:12 UTC, shumkov commented on lib/StateRepositoryInterface.js
> + * @name StateRepository#fetchIdentityIdsByPublicKeys
`fetchIdentityIdsByPublicKeyHashes`

2020-09-10 11:15 UTC, shumkov commented on lib/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeysUniquenessFactory.js
> +    if (identitiesByKeys) {
It could be `null` or `undefined`?

2020-09-10 22:26 UTC, shumkov requested changes

2020-09-10 22:26 UTC, shumkov commented on lib/StateRepositoryInterface.js
> + * @name StateRepository#storeIdentityIdPublicKeyHashes
storeIdentityPublicKeyHashes

2020-09-10 22:26 UTC, shumkov commented on lib/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeysUniquenessFactory.js
> +    Object.entries(identitiesByKeys).forEach(([identityPublicKeyHash, identityId]) => {
Let's add filter and then forEach?

2020-09-11 08:32 UTC, shuplenkov commented on lib/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeysUniquenessFactory.js
> +    Object.entries(identitiesByKeys).forEach(([identityPublicKeyHash, identityId]) => {
it would be 2 cycles instead of one

2020-09-15 10:41 UTC, shumkov approved these changes
LGTM! 👍

2020-09-15 12:12 UTC, merged