feat: add `protocolVersion` option to main class
dashevo/js-dpp pull request #329
Opened 2021-07-29 08:56 UTC by jawid-h

## Issue being fixed or feature implemented

Adding an ability to pass external `protocolVersion` as an option

## What was done?

- added `protocolVersion` 
- added setter for it

## How Has This Been Tested?

Unit tests

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-07-29 09:52 UTC, shumkov requested changes
Use protocol version from a DPP instance to create data in factories.

2021-07-29 09:52 UTC, shumkov commented on lib/DashPlatformProtocol.js
> +
Add a getter

2021-07-29 16:32 UTC, shumkov commented on lib/DashPlatformProtocol.js
>          this.jsonSchemaValidator,
Does it make sense to pass `jsonSchemaValidator` and `stateRepository` separately since we can use getters inside?

2021-07-29 16:33 UTC, shumkov commented on test/unit/stateTransition/validation/validateStateTransitionDataFactory.spec.js
> +      getProtocolVersion: () => 0,
I would recommend to create a mock and use it everywhere in tests

2021-07-30 09:57 UTC, shumkov requested changes

2021-07-30 09:57 UTC, shumkov commented on lib/stateTransition/StateTransitionFacade.js
> +    this.validator = dpp.getJsonSchemaValidator();
Why not just a local variables?

2021-07-30 09:57 UTC, shumkov commented on lib/document/DocumentFacade.js
> +    this.stateRepository = dpp.getStateRepository();
Why not local variable?

2021-07-30 09:57 UTC, shumkov commented on lib/test/mocks/createDPPMock.js
>   * @param {Sandbox} sinonSandbox
Mark as an optional?

2021-07-30 10:44 UTC, jawid-h commented on lib/stateTransition/StateTransitionFacade.js
> +    this.validator = dpp.getJsonSchemaValidator();
They are being used in other methods

2021-07-30 10:44 UTC, jawid-h commented on lib/document/DocumentFacade.js
> +    this.stateRepository = dpp.getStateRepository();
They are being used in other methods

2021-07-30 12:22 UTC, shumkov approved these changes
LGTM! 👍

2021-07-30 12:43 UTC, merged